### 1. Importing

In [1]:
import pandas as pd
import altair as alt
import numpy as np

In [6]:
prop_type_totals = pd.read_csv('prop_type_totals_clean.csv', parse_dates=['Years'])
injury_by_cause = pd.read_csv('injury_by_cause_clean.csv', parse_dates=['Years'])
fire_by_cause = pd.read_csv('fire_causes_clean.csv', parse_dates=['Years'])
death_by_cause = pd.read_csv('death_by_cause_clean.csv', parse_dates=['Years'])
cost_by_cause = pd.read_csv('cost_by_cause_clean.csv', parse_dates=['Years'])

These cleaned up versions are on Google Drive (fire_causes:https://drive.google.com/file/d/1tKOuNra0odnUJUF32GCL_RwWOH_mw4v6/view?usp=sharing,
injury_by_cause:https://drive.google.com/file/d/1ew9uDiNTYj9F3BkiwQ8yM3Yiyk5bINd5/view?usp=sharing,
death_by_cause: https://drive.google.com/file/d/1acGP-pViYzRYlDyOCy0c5vQifRVnv4c9/view?usp=sharing,
cost_by_cause: https://drive.google.com/file/d/15uQvcPNoOBbaHRWcl-OKuws_2Jah0b_J/view?usp=sharing)

### 2. Checking that they imported ok

Everything ended up importing nicely!

In [8]:
prop_type_totals.head()

,Years,Overall Res Building Fires,1 & 2 Family Fires,Multifamily Fires,Overall Deaths,1 & 2 Family Deaths,Multifamily Deaths,Overall Injuries,1 & 2 Family Injuries,Multifamily Injuries,Overall Dollars Los,1 & 2 Family Dollars Loss,Multifamily Dollars Loss
0,2003-01-01,381200,249400,108800,3000,2480,380,13425,9200,3650,8376800000,6603600000,1362200000
1,2004-01-01,389800,254600,111700,3050,2485,425,13650,9275,3775,8097100000,6227800000,1509500000
2,2005-01-01,376500,245900,107000,2895,2225,510,13375,8950,3800,9013900000,6929100000,1654400000
3,2006-01-01,392700,253800,113900,2490,1925,445,12550,8225,3725,8932300000,6960600000,1570900000
4,2007-01-01,390300,260700,104600,2765,2285,405,13525,9125,3875,9353500000,7520600000,1445700000

In [5]:
prop_type_totals.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Years                       19 non-null     datetime64[ns]
 1   Overall Res Building Fires  19 non-null     int64
 2   1 & 2 Family Fires          19 non-null     int64
 3   Multifamily Fires           19 non-null     int64
 4   Overall Deaths              19 non-null     int64
 5   1 & 2 Family Deaths         19 non-null     int64
 6   Multifamily Deaths          19 non-null     int64
 7   Overall Injuries            19 non-null     int64
 8   1 & 2 Family Injuries       19 non-null     int64
 9   Multifamily Injuries        19 non-null     int64
 10  Overall Dollars Los         19 non-null     int64
 11  1 & 2 Family Dollars Loss   19 non-null     int64
 12  Multifamily Dollars Loss    19 non-null     int64
dtypes: datetime64[ns](1), int64(12)
memory usage: 2.1 KB

In [9]:
injury_by_cause.head()

,Years,Overall Intentional,1 & 2 Fam Intentional,Multi Fam Intentional,Overall Playing with Heat Source,1 &2 Fam Playing with Heat Source,Multi Fam Playing with Heat Source,Overall Smoking,1 & 2 Fam Smoking,Mulit Fam Smoking,...,Multi Fam Exposure,Overall Equipment Malfunction,1 & 2 Fam Equipment Malfunction,Multi Fam Equipment Malfunction,"Overall Other Unintentional, Careless","1 & 2 Fam Other Unintentional, Careless","Multi Fam Other Unintentional, Careless",Overall Cause Under Investigation,1 & 2 Fam Cause Under Investigation,Multi Fam Cause Under Investigation
0,2003-01-01,875,570,255,500,405,95,1025,655,305,...,15,900,585,295,1550,1150,340,275,225,45
1,2004-01-01,850,625,215,500,345,135,1050,600,355,...,10,1150,815,270,1500,1070,390,325,240,75
2,2005-01-01,925,615,280,325,200,115,1025,505,405,...,20,1050,715,295,1500,1075,365,400,275,100
3,2006-01-01,750,440,255,425,315,110,1150,620,425,...,10,900,560,310,1350,930,355,375,255,95
4,2007-01-01,950,580,310,400,330,80,950,590,315,...,5,825,545,265,1500,1110,360,425,290,120

In [13]:
injury_by_cause.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 46 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Years                                    19 non-null     datetime64[ns]
 1   Overall Intentional                      19 non-null     int64
 2   1 & 2 Fam Intentional                    19 non-null     int64
 3   Multi Fam Intentional                    19 non-null     int64
 4   Overall Playing with Heat Source         19 non-null     int64
 5   1 &2 Fam Playing with Heat Source        19 non-null     int64
 6   Multi Fam Playing with Heat Source       19 non-null     int64
 7   Overall Smoking                          19 non-null     int64
 8   1 & 2 Fam Smoking                        19 non-null     int64
 9   Mulit Fam Smoking                        19 non-null     int64
 10  Overall Heating                          19 non-null     int64
 11  1 & 2 Fam Heating                        19 non-null     int64
 12  Multi Fam Heating                        19 non-null     int64
 13  Overall Cooking                          19 non-null     int64
 14  1 & 2 Fam Cooking                        19 non-null     int64
 15  Multi Fam Cooking                        19 non-null     int64
 16  Overall Electrical Malfunction           19 non-null     int64
 17  1 & 2 Fam Electrical Malfunction         19 non-null     int64
 18  Multi Fam Electrical Malfunction         19 non-null     int64
 19  Overall Appliances                       19 non-null     int64
 20  1 & 2 Fam Appliances                     19 non-null     int64
 21  Multi Fam Appliances                     19 non-null     int64
 22  Overall Open Flame                       19 non-null     int64
 23  1 & 2 Open Flame                         19 non-null     int64
 24  Multi Fam Open Flame                     19 non-null     int64
 25  Overall Other Heat                       19 non-null     int64
 26  1 & 2 Fam Other Heat                     19 non-null     int64
 27  Multi Fam Other Heat                     19 non-null     int64
 28  Overall Other Equipment                  19 non-null     int64
 29  1 & 2 Fam Other Equipment                19 non-null     int64
 30  Multi Fam Other Equipment                19 non-null     int64
 31  Overall Natural                          19 non-null     int64
 32  1 & 2 Fam Natural                        19 non-null     int64
 33  Multi Fam Natural                        19 non-null     int64
 34  Overall Exposure                         19 non-null     int64
 35  1 & 2 Fam Explosure                      19 non-null     int64
 36  Multi Fam Exposure                       19 non-null     int64
 37  Overall Equipment Malfunction            19 non-null     int64
 38  1 & 2 Fam Equipment Malfunction          19 non-null     int64
 39  Multi Fam Equipment Malfunction          19 non-null     int64
 40  Overall Other Unintentional, Careless    19 non-null     int64
 41  1 & 2 Fam Other Unintentional, Careless  19 non-null     int64
 42  Multi Fam Other Unintentional, Careless  19 non-null     int64
 43  Overall Cause Under Investigation        19 non-null     int64
 44  1 & 2 Fam Cause Under Investigation      19 non-null     int64
 45  Multi Fam Cause Under Investigation      19 non-null     int64
dtypes: datetime64[ns](1), int64(45)
memory usage: 7.0 KB

In [10]:
fire_by_cause.head()

,Years,Overall Intentional,1 & 2 Fam Intentional,Multi Fam Intentional,Overall Playing with Heat Source,1 &2 Fam Playing with Heat Source,Multi Fam Playing with Heat Source,Overall Smoking,1 & 2 Fam Smoking,Mulit Fam Smoking,...,Overall Equipment Malfunction,1 & 2 Fam Equipment Malfunction,Multi Fam Equipment Malfunction,"Overall Other Unintentional, Careless","1 & 2 Fam Other Unintentional, Careless","Multi Fam Other Unintentional, Careless",Overall Cause Under Investigation,1 & 2 Fam Cause Under Investigation,Multi Fam Cause Under Investigation,Total Residential*
0,2003-01-01,17400,17400,3200,3500,2800,700,8900,5600,2700,...,16100,12200,3300,22000,17100,4000,2200,1800,400,381200
1,2004-01-01,17500,17500,3000,3100,2400,600,9000,5600,2800,...,16000,12000,3300,22300,17400,4000,2400,1900,400,389800
2,2005-01-01,18000,18000,3300,2900,2300,600,8700,5400,2600,...,15100,11100,3400,22500,17300,4100,2900,2200,500,376500
3,2006-01-01,18100,18100,3200,3200,2500,700,9700,6000,3100,...,14700,10800,3400,23400,18200,4100,3300,2500,600,392700
4,2007-01-01,19000,19000,3400,3100,2400,600,8900,5700,2700,...,15200,11400,3100,25400,20200,4000,3800,2900,700,390300

In [14]:
fire_by_cause.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 47 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Years                                    19 non-null     datetime64[ns]
 1   Overall Intentional                      19 non-null     int64
 2   1 & 2 Fam Intentional                    19 non-null     int64
 3   Multi Fam Intentional                    19 non-null     int64
 4   Overall Playing with Heat Source         19 non-null     int64
 5   1 &2 Fam Playing with Heat Source        19 non-null     int64
 6   Multi Fam Playing with Heat Source       19 non-null     int64
 7   Overall Smoking                          19 non-null     int64
 8   1 & 2 Fam Smoking                        19 non-null     int64
 9   Mulit Fam Smoking                        19 non-null     int64
 10  Overall Heating                          19 non-null     int64
 11  1 & 2 Fam Heating                        19 non-null     int64
 12  Multi Fam Heating                        19 non-null     int64
 13  Overall Cooking                          19 non-null     int64
 14  1 & 2 Fam Cooking                        19 non-null     int64
 15  Multi Fam Cooking                        19 non-null     int64
 16  Overall Electrical Malfunction           19 non-null     int64
 17  1 & 2 Fam Electrical Malfunction         19 non-null     int64
 18  Multi Fam Electrical Malfunction         19 non-null     int64
 19  Overall Appliances                       19 non-null     int64
 20  1 & 2 Fam Appliances                     19 non-null     int64
 21  Multi Fam Appliances                     19 non-null     int64
 22  Overall Open Flame                       19 non-null     int64
 23  1 & 2 Open Flame                         19 non-null     int64
 24  Multi Fam Open Flame                     19 non-null     int64
 25  Overall Other Heat                       19 non-null     int64
 26  1 & 2 Fam Other Heat                     19 non-null     int64
 27  Multi Fam Other Heat                     19 non-null     int64
 28  Overall Other Equipment                  19 non-null     int64
 29  1 & 2 Fam Other Equipment                19 non-null     int64
 30  Multi Fam Other Equipment                19 non-null     int64
 31  Overall Natural                          19 non-null     int64
 32  1 & 2 Fam Natural                        19 non-null     int64
 33  Multi Fam Natural                        19 non-null     int64
 34  Overall Exposure                         19 non-null     int64
 35  1 & 2 Fam Explosure                      19 non-null     int64
 36  Multi Fam Exposure                       19 non-null     int64
 37  Overall Equipment Malfunction            19 non-null     int64
 38  1 & 2 Fam Equipment Malfunction          19 non-null     int64
 39  Multi Fam Equipment Malfunction          19 non-null     int64
 40  Overall Other Unintentional, Careless    19 non-null     int64
 41  1 & 2 Fam Other Unintentional, Careless  19 non-null     int64
 42  Multi Fam Other Unintentional, Careless  19 non-null     int64
 43  Overall Cause Under Investigation        19 non-null     int64
 44  1 & 2 Fam Cause Under Investigation      19 non-null     int64
 45  Multi Fam Cause Under Investigation      19 non-null     int64
 46  Total Residential*                       19 non-null     int64
dtypes: datetime64[ns](1), int64(46)
memory usage: 7.1 KB

In [11]:
death_by_cause.head()

,Years,Overall Intentional,1 & 2 Fam Intentional,Multi Fam Intentional,Overall Playing with Heat Source,1 &2 Fam Playing with Heat Source,Multi Fam Playing with Heat Source,Overall Smoking,1 & 2 Fam Smoking,Mulit Fam Smoking,...,Multi Fam Exposure,Overall Equipment Malfunction,1 & 2 Fam Equipment Malfunction,Multi Fam Equipment Malfunction,"Overall Other Unintentional, Careless","1 & 2 Fam Other Unintentional, Careless","Multi Fam Other Unintentional, Careless",Overall Cause Under Investigation,1 & 2 Fam Cause Under Investigation,Multi Fam Cause Under Investigation
0,2003-01-01,265,220,40,130,130,NaN,500,320,120,...,NaN,100,95,5.0,440,365,55,215,205,5
1,2004-01-01,255,220,35,60,45,5.0,505,380,95,...,NaN,155,105,25.0,430,350,60,195,170,25
2,2005-01-01,350,280,55,55,30,20.0,510,350,120,...,15.0,120,90,30.0,410,370,30,205,160,40
3,2006-01-01,250,175,50,80,75,10.0,485,360,90,...,10.0,90,65,20.0,365,310,35,165,120,35
4,2007-01-01,310,265,35,55,50,NaN,470,340,100,...,NaN,120,115,5.0,380,325,50,240,205,35

In [15]:
death_by_cause.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 46 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Years                                    19 non-null     datetime64[ns]
 1   Overall Intentional                      19 non-null     int64
 2   1 & 2 Fam Intentional                    19 non-null     int64
 3   Multi Fam Intentional                    19 non-null     int64
 4   Overall Playing with Heat Source         19 non-null     int64
 5   1 &2 Fam Playing with Heat Source        19 non-null     int64
 6   Multi Fam Playing with Heat Source       10 non-null     float64
 7   Overall Smoking                          19 non-null     int64
 8   1 & 2 Fam Smoking                        19 non-null     int64
 9   Mulit Fam Smoking                        19 non-null     int64
 10  Overall Heating                          19 non-null     int64
 11  1 & 2 Fam Heating                        19 non-null     int64
 12  Multi Fam Heating                        19 non-null     int64
 13  Overall Cooking                          19 non-null     int64
 14  1 & 2 Fam Cooking                        19 non-null     int64
 15  Multi Fam Cooking                        19 non-null     int64
 16  Overall Electrical Malfunction           19 non-null     int64
 17  1 & 2 Fam Electrical Malfunction         19 non-null     int64
 18  Multi Fam Electrical Malfunction         19 non-null     int64
 19  Overall Appliances                       19 non-null     int64
 20  1 & 2 Fam Appliances                     19 non-null     int64
 21  Multi Fam Appliances                     16 non-null     float64
 22  Overall Open Flame                       19 non-null     int64
 23  1 & 2 Open Flame                         19 non-null     int64
 24  Multi Fam Open Flame                     19 non-null     int64
 25  Overall Other Heat                       19 non-null     int64
 26  1 & 2 Fam Other Heat                     19 non-null     int64
 27  Multi Fam Other Heat                     19 non-null     int64
 28  Overall Other Equipment                  19 non-null     int64
 29  1 & 2 Fam Other Equipment                19 non-null     int64
 30  Multi Fam Other Equipment                13 non-null     float64
 31  Overall Natural                          19 non-null     int64
 32  1 & 2 Fam Natural                        19 non-null     int64
 33  Multi Fam Natural                        2 non-null      float64
 34  Overall Exposure                         18 non-null     float64
 35  1 & 2 Fam Explosure                      18 non-null     float64
 36  Multi Fam Exposure                       11 non-null     float64
 37  Overall Equipment Malfunction            19 non-null     int64
 38  1 & 2 Fam Equipment Malfunction          19 non-null     int64
 39  Multi Fam Equipment Malfunction          17 non-null     float64
 40  Overall Other Unintentional, Careless    19 non-null     int64
 41  1 & 2 Fam Other Unintentional, Careless  19 non-null     int64
 42  Multi Fam Other Unintentional, Careless  19 non-null     int64
 43  Overall Cause Under Investigation        19 non-null     int64
 44  1 & 2 Fam Cause Under Investigation      19 non-null     int64
 45  Multi Fam Cause Under Investigation      19 non-null     int64
dtypes: datetime64[ns](1), float64(8), int64(37)
memory usage: 7.0 KB

In [12]:
cost_by_cause.head()

,Years,Overall Intentional,1 & 2 Fam Intentional,Multi Fam Intentional,Overall Playing with Heat Source,1 &2 Fam Playing with Heat Source,Multi Fam Playing with Heat Source,Overall Smoking,1 & 2 Fam Smoking,Mulit Fam Smoking,...,Multi Fam Exposure,Overall Equipment Malfunction,1 & 2 Fam Equipment Malfunction,Multi Fam Equipment Malfunction,"Overall Other Unintentional, Careless","1 & 2 Fam Other Unintentional, Careless","Multi Fam Other Unintentional, Careless",Overall Cause Under Investigation,1 & 2 Fam Cause Under Investigation,Multi Fam Cause Under Investigation
0,2003-01-01,761200000,542300000,153100000,180200000,142600000,34200000,363700000,243000000,103000000,...,116500000,543000000,429800000,96300000,1140600000,962900000,138200000,252100000,220000000,26400000
1,2004-01-01,716600000,554900000,125500000,154600000,106900000,43700000,375800000,228500000,133500000,...,110100000,469600000,380800000,72100000,1114600000,848800000,209000000,293600000,214100000,74800000
2,2005-01-01,784600000,527700000,212000000,175700000,122100000,48700000,423600000,228900000,158400000,...,104100000,553900000,433000000,82800000,1145900000,967600000,148800000,451100000,313100000,101700000
3,2006-01-01,719900000,527100000,104200000,152300000,108400000,40500000,434000000,239200000,176100000,...,76700000,504800000,389200000,96600000,1204100000,963600000,194200000,405000000,293100000,95100000
4,2007-01-01,630800000,433400000,171000000,121900000,81900000,37400000,345800000,202000000,132000000,...,109700000,440600000,339300000,68400000,1130600000,930200000,144400000,357400000,233800000,110400000

In [16]:
cost_by_cause.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 46 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Years                                    19 non-null     datetime64[ns]
 1   Overall Intentional                      19 non-null     int64
 2   1 & 2 Fam Intentional                    19 non-null     int64
 3   Multi Fam Intentional                    19 non-null     int64
 4   Overall Playing with Heat Source         19 non-null     int64
 5   1 &2 Fam Playing with Heat Source        19 non-null     int64
 6   Multi Fam Playing with Heat Source       19 non-null     int64
 7   Overall Smoking                          19 non-null     int64
 8   1 & 2 Fam Smoking                        19 non-null     int64
 9   Mulit Fam Smoking                        19 non-null     int64
 10  Overall Heating                          19 non-null     int64
 11  1 & 2 Fam Heating                        19 non-null     int64
 12  Multi Fam Heating                        19 non-null     int64
 13  Overall Cooking                          19 non-null     int64
 14  1 & 2 Fam Cooking                        19 non-null     int64
 15  Multi Fam Cooking                        19 non-null     int64
 16  Overall Electrical Malfunction           19 non-null     int64
 17  1 & 2 Fam Electrical Malfunction         19 non-null     int64
 18  Multi Fam Electrical Malfunction         19 non-null     int64
 19  Overall Appliances                       19 non-null     int64
 20  1 & 2 Fam Appliances                     19 non-null     int64
 21  Multi Fam Appliances                     19 non-null     int64
 22  Overall Open Flame                       19 non-null     int64
 23  1 & 2 Open Flame                         19 non-null     int64
 24  Multi Fam Open Flame                     19 non-null     int64
 25  Overall Other Heat                       19 non-null     int64
 26  1 & 2 Fam Other Heat                     19 non-null     int64
 27  Multi Fam Other Heat                     19 non-null     int64
 28  Overall Other Equipment                  19 non-null     int64
 29  1 & 2 Fam Other Equipment                19 non-null     int64
 30  Multi Fam Other Equipment                19 non-null     int64
 31  Overall Natural                          19 non-null     int64
 32  1 & 2 Fam Natural                        19 non-null     int64
 33  Multi Fam Natural                        19 non-null     int64
 34  Overall Exposure                         19 non-null     int64
 35  1 & 2 Fam Explosure                      19 non-null     int64
 36  Multi Fam Exposure                       19 non-null     int64
 37  Overall Equipment Malfunction            19 non-null     int64
 38  1 & 2 Fam Equipment Malfunction          19 non-null     int64
 39  Multi Fam Equipment Malfunction          19 non-null     int64
 40  Overall Other Unintentional, Careless    19 non-null     int64
 41  1 & 2 Fam Other Unintentional, Careless  19 non-null     int64
 42  Multi Fam Other Unintentional, Careless  19 non-null     int64
 43  Overall Cause Under Investigation        19 non-null     int64
 44  1 & 2 Fam Cause Under Investigation      19 non-null     int64
 45  Multi Fam Cause Under Investigation      19 non-null     int64
dtypes: datetime64[ns](1), int64(45)
memory usage: 7.0 KB

### 3. Creating a new dataframe

Now that I know what columns I want to focus on, I'm going to create new dataframes that subset the data to the causes that I want to focus on. I'll also be renaming the columns so that I can combine the dataframes all together much easier

In [21]:
fire_by_cause_focused = fire_by_cause[
    ['Years','1 & 2 Fam Heating', 'Multi Fam Heating', '1 & 2 Fam Cooking', 'Multi Fam Cooking', '1 & 2 Fam Electrical Malfunction']
].copy()

In [38]:
fire_by_cause_focused.columns  = [
    'Years',
    '1 & 2 Fam Heating Fires',
    'Multi Fam Heating Fires',
    '1 & 2 Fam Cooking Fires',
    'MultiFam Cooking Fires',
    '1 & 2 Fam Electrical Malfunction Fires'
]

In [39]:
fire_by_cause_focused.head()

,Years,1 & 2 Fam Heating Fires,Multi Fam Heating Fires,1 & 2 Fam Cooking Fires,MultiFam Cooking Fires,1 & 2 Fam Electrical Malfunction Fires
0,2003-01-01,49800,9400,71600,67400,22600
1,2004-01-01,49100,9900,77000,71000,23300
2,2005-01-01,44500,8200,73600,67200,24200
3,2006-01-01,44300,7800,77800,74100,25600
4,2007-01-01,46000,6800,77100,68400,26500

In [23]:
injury_by_cause_focused = injury_by_cause[
    ['Years','1 & 2 Fam Heating', 'Multi Fam Heating', '1 & 2 Fam Cooking', 'Multi Fam Cooking', '1 & 2 Fam Electrical Malfunction']
].copy()

In [52]:
injury_by_cause_focused.columns  = [
    'Years1',
    '1 & 2 Fam Heating Injuries',
    'Multi Fam Heating Injuries',
    '1 & 2 Fam Cooking Injuries',
    'MultiFam Cooking Injuries',
    '1 & 2 Fam Electrical Malfunction Injuries'
]

In [53]:
injury_by_cause_focused.head()

,Years1,1 & 2 Fam Heating Injuries,Multi Fam Heating Injuries,1 & 2 Fam Cooking Injuries,MultiFam Cooking Injuries,1 & 2 Fam Electrical Malfunction Injuries
0,2003-01-01,515,110,1675,1200,695
1,2004-01-01,540,90,1780,1295,735
2,2005-01-01,475,115,1720,1195,915
3,2006-01-01,465,80,1635,1185,795
4,2007-01-01,575,100,1800,1380,905

In [25]:
death_by_cause_focused = death_by_cause[
    ['Years','1 & 2 Fam Heating', 'Multi Fam Heating', '1 & 2 Fam Cooking', 'Multi Fam Cooking', '1 & 2 Fam Electrical Malfunction']
].copy()

In [54]:
death_by_cause_focused.columns  = [
    'Years2',
    '1 & 2 Fam Heating Death',
    'Multi Fam Heating Death',
    '1 & 2 Fam Cooking Death',
    'MultiFam Cooking Death',
    '1 & 2 Fam Electrical Malfunction Death'
]

In [55]:
death_by_cause_focused.head()

,Years2,1 & 2 Fam Heating Death,Multi Fam Heating Death,1 & 2 Fam Cooking Death,MultiFam Cooking Death,1 & 2 Fam Electrical Malfunction Death
0,2003-01-01,135,10,95,10,335
1,2004-01-01,185,10,120,65,315
2,2005-01-01,205,20,75,55,270
3,2006-01-01,155,15,55,60,275
4,2007-01-01,160,15,80,25,270

In [28]:
cost_by_cause_focused = cost_by_cause[
    ['Years','1 & 2 Fam Heating', 'Multi Fam Heating', '1 & 2 Fam Cooking', 'Multi Fam Cooking', '1 & 2 Fam Electrical Malfunction']
].copy()

In [56]:
cost_by_cause_focused.columns  = [
    'Years3',
    '1 & 2 Fam Heating Cost',
    'Multi Fam Heating Cost',
    '1 & 2 Fam Cooking Cost',
    'MultiFam Cooking Cost',
    '1 & 2 Fam Electrical Malfunction Cost'
]

In [57]:
cost_by_cause_focused.head()

,Years3,1 & 2 Fam Heating Cost,Multi Fam Heating Cost,1 & 2 Fam Cooking Cost,MultiFam Cooking Cost,1 & 2 Fam Electrical Malfunction Cost
0,2003-01-01,435200000,35300000,266600000,96600000,1033800000
1,2004-01-01,332800000,60600000,220500000,85900000,1075900000
2,2005-01-01,338600000,52800000,265500000,88700000,1276700000
3,2006-01-01,377100000,32900000,229300000,84700000,1135500000
4,2007-01-01,285600000,33500000,214400000,75000000,1106300000

In [65]:
cause_and_effect_fires = pd.concat([
    fire_by_cause_focused, 
    injury_by_cause_focused, 
    death_by_cause_focused, 
    cost_by_cause_focused,
    prop_type_totals
], axis=1)

In [69]:
cause_and_effect_fires.head()

,Years,1 & 2 Fam Heating Fires,Multi Fam Heating Fires,1 & 2 Fam Cooking Fires,MultiFam Cooking Fires,1 & 2 Fam Electrical Malfunction Fires,1 & 2 Fam Heating Injuries,Multi Fam Heating Injuries,1 & 2 Fam Cooking Injuries,MultiFam Cooking Injuries,...,MultiFam Cooking Death,1 & 2 Fam Electrical Malfunction Death,1 & 2 Fam Heating Cost,Multi Fam Heating Cost,1 & 2 Fam Cooking Cost,MultiFam Cooking Cost,1 & 2 Fam Electrical Malfunction Cost,Years,1 & 2 Family Fires,Multifamily Fires
0,2003-01-01,49800,9400,71600,67400,22600,515,110,1675,1200,...,10,335,435200000,35300000,266600000,96600000,1033800000,2003-01-01,249400,108800
1,2004-01-01,49100,9900,77000,71000,23300,540,90,1780,1295,...,65,315,332800000,60600000,220500000,85900000,1075900000,2004-01-01,254600,111700
2,2005-01-01,44500,8200,73600,67200,24200,475,115,1720,1195,...,55,270,338600000,52800000,265500000,88700000,1276700000,2005-01-01,245900,107000
3,2006-01-01,44300,7800,77800,74100,25600,465,80,1635,1185,...,60,275,377100000,32900000,229300000,84700000,1135500000,2006-01-01,253800,113900
4,2007-01-01,46000,6800,77100,68400,26500,575,100,1800,1380,...,25,270,285600000,33500000,214400000,75000000,1106300000,2007-01-01,260700,104600

In [70]:
cause_and_effect_fires = cause_and_effect_fires.drop([
    'Years1',
    'Years2',
    'Years3',
    '1 & 2 Family Deaths',
    'Multifamily Deaths',
    'Overall Injuries',
    '1 & 2 Family Injuries',
    'Multifamily Injuries',
    'Overall Dollars Los',
    '1 & 2 Family Dollars Loss',
    'Multifamily Dollars Loss',
    'Overall Deaths',
    'Overall Res Building Fires'
], axis=1)

KeyError: "['Years1' 'Years2' 'Years3' '1 & 2 Family Deaths' 'Multifamily Deaths'\n 'Overall Injuries' '1 & 2 Family Injuries' 'Multifamily Injuries'\n 'Overall Dollars Los' '1 & 2 Family Dollars Loss'\n 'Multifamily Dollars Loss' 'Overall Deaths' 'Overall Res Building Fires'] not found in axis"

In [71]:
cause_and_effect_fires.head()

,Years,1 & 2 Fam Heating Fires,Multi Fam Heating Fires,1 & 2 Fam Cooking Fires,MultiFam Cooking Fires,1 & 2 Fam Electrical Malfunction Fires,1 & 2 Fam Heating Injuries,Multi Fam Heating Injuries,1 & 2 Fam Cooking Injuries,MultiFam Cooking Injuries,...,MultiFam Cooking Death,1 & 2 Fam Electrical Malfunction Death,1 & 2 Fam Heating Cost,Multi Fam Heating Cost,1 & 2 Fam Cooking Cost,MultiFam Cooking Cost,1 & 2 Fam Electrical Malfunction Cost,Years,1 & 2 Family Fires,Multifamily Fires
0,2003-01-01,49800,9400,71600,67400,22600,515,110,1675,1200,...,10,335,435200000,35300000,266600000,96600000,1033800000,2003-01-01,249400,108800
1,2004-01-01,49100,9900,77000,71000,23300,540,90,1780,1295,...,65,315,332800000,60600000,220500000,85900000,1075900000,2004-01-01,254600,111700
2,2005-01-01,44500,8200,73600,67200,24200,475,115,1720,1195,...,55,270,338600000,52800000,265500000,88700000,1276700000,2005-01-01,245900,107000
3,2006-01-01,44300,7800,77800,74100,25600,465,80,1635,1185,...,60,275,377100000,32900000,229300000,84700000,1135500000,2006-01-01,253800,113900
4,2007-01-01,46000,6800,77100,68400,26500,575,100,1800,1380,...,25,270,285600000,33500000,214400000,75000000,1106300000,2007-01-01,260700,104600

### 4. Prepping for charts

So I realized that I need to narrow down my tables even more so that it's easier for me to make by charts. So I made more data frames by subsetting from the new dataframe we just made.

In [75]:
cause_and_effect_fires.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 24 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Years                                      19 non-null     datetime64[ns]
 1   1 & 2 Fam Heating Fires                    19 non-null     int64
 2   Multi Fam Heating Fires                    19 non-null     int64
 3   1 & 2 Fam Cooking Fires                    19 non-null     int64
 4   MultiFam Cooking Fires                     19 non-null     int64
 5   1 & 2 Fam Electrical Malfunction Fires     19 non-null     int64
 6   1 & 2 Fam Heating Injuries                 19 non-null     int64
 7   Multi Fam Heating Injuries                 19 non-null     int64
 8   1 & 2 Fam Cooking Injuries                 19 non-null     int64
 9   MultiFam Cooking Injuries                  19 non-null     int64
 10  1 & 2 Fam Electrical Malfunction Injuries  19 non-null     int64
 11  1 & 2 Fam Heating Death                    19 non-null     int64
 12  Multi Fam Heating Death                    19 non-null     int64
 13  1 & 2 Fam Cooking Death                    19 non-null     int64
 14  MultiFam Cooking Death                     19 non-null     int64
 15  1 & 2 Fam Electrical Malfunction Death     19 non-null     int64
 16  1 & 2 Fam Heating Cost                     19 non-null     int64
 17  Multi Fam Heating Cost                     19 non-null     int64
 18  1 & 2 Fam Cooking Cost                     19 non-null     int64
 19  MultiFam Cooking Cost                      19 non-null     int64
 20  1 & 2 Fam Electrical Malfunction Cost      19 non-null     int64
 21  Years                                      19 non-null     datetime64[ns]
 22  1 & 2 Family Fires                         19 non-null     int64
 23  Multifamily Fires                          19 non-null     int64
dtypes: datetime64[ns](2), int64(22)
memory usage: 3.7 KB

In [76]:
total_fires = cause_and_effect_fires[
    ['Years',
     '1 & 2 Family Fires',
     'Multifamily Fires',
     '1 & 2 Fam Heating Fires',
     'Multi Fam Heating Fires',
     '1 & 2 Fam Cooking Fires',
     'MultiFam Cooking Fires',
     '1 & 2 Fam Electrical Malfunction Fires']
].copy()

In [78]:
total_fires = total_fires.loc[:,~total_fires.columns.duplicated()].copy()

In [80]:
total_fires.head()

,Years,1 & 2 Family Fires,Multifamily Fires,1 & 2 Fam Heating Fires,Multi Fam Heating Fires,1 & 2 Fam Cooking Fires,MultiFam Cooking Fires,1 & 2 Fam Electrical Malfunction Fires
0,2003-01-01,249400,108800,49800,9400,71600,67400,22600
1,2004-01-01,254600,111700,49100,9900,77000,71000,23300
2,2005-01-01,245900,107000,44500,8200,73600,67200,24200
3,2006-01-01,253800,113900,44300,7800,77800,74100,25600
4,2007-01-01,260700,104600,46000,6800,77100,68400,26500

In [100]:
fam_1_2_heating = cause_and_effect_fires[
    ['Years',
     '1 & 2 Fam Heating Fires',
     '1 & 2 Fam Heating Injuries',
     '1 & 2 Fam Heating Death']
].copy()
fam_1_2_heating = fam_1_2_heating.loc[:,~fam_1_2_heating.columns.duplicated()].copy()

In [104]:
fam_1_2_heating.head()

,Years,1 & 2 Fam Heating Fires,1 & 2 Fam Heating Injuries,1 & 2 Fam Heating Death
0,2003-01-01,49800,515,135
1,2004-01-01,49100,540,185
2,2005-01-01,44500,475,205
3,2006-01-01,44300,465,155
4,2007-01-01,46000,575,160

In [99]:
multi_fam_heating = cause_and_effect_fires[
    ['Years',
     'Multi Fam Heating Fires',
     'Multi Fam Heating Injuries',
     'Multi Fam Heating Death']
].copy()
multi_fam_heating = multi_fam_heating.loc[:,~multi_fam_heating.columns.duplicated()].copy()

In [105]:
multi_fam_heating.head()

,Years,Multi Fam Heating Fires,Multi Fam Heating Injuries,Multi Fam Heating Death
0,2003-01-01,9400,110,10
1,2004-01-01,9900,90,10
2,2005-01-01,8200,115,20
3,2006-01-01,7800,80,15
4,2007-01-01,6800,100,15

In [101]:
fam_1_2_cooking = cause_and_effect_fires[
    ['Years',
     '1 & 2 Fam Cooking Fires',
     '1 & 2 Fam Cooking Injuries',
     '1 & 2 Fam Cooking Death']
].copy()
fam_1_2_cooking = fam_1_2_cooking.loc[:,~fam_1_2_cooking.columns.duplicated()].copy()

In [106]:
fam_1_2_cooking.head()

,Years,1 & 2 Fam Cooking Fires,1 & 2 Fam Cooking Injuries,1 & 2 Fam Cooking Death
0,2003-01-01,71600,1675,95
1,2004-01-01,77000,1780,120
2,2005-01-01,73600,1720,75
3,2006-01-01,77800,1635,55
4,2007-01-01,77100,1800,80

In [102]:
multi_fam_cooking = cause_and_effect_fires[
    ['Years',
     'MultiFam Cooking Fires',
     'MultiFam Cooking Injuries',
     'MultiFam Cooking Death']
].copy()
multi_fam_cooking = multi_fam_cooking.loc[:,~multi_fam_cooking.columns.duplicated()].copy()

In [107]:
multi_fam_cooking.head()

,Years,MultiFam Cooking Fires,MultiFam Cooking Injuries,MultiFam Cooking Death
0,2003-01-01,67400,1200,10
1,2004-01-01,71000,1295,65
2,2005-01-01,67200,1195,55
3,2006-01-01,74100,1185,60
4,2007-01-01,68400,1380,25

In [103]:
fam_1_2_electrical = cause_and_effect_fires[
    ['Years',
     '1 & 2 Fam Electrical Malfunction Fires', 
     '1 & 2 Fam Electrical Malfunction Injuries', 
     '1 & 2 Fam Electrical Malfunction Death']
].copy()
fam_1_2_electrical = fam_1_2_electrical.loc[:,~fam_1_2_electrical.columns.duplicated()].copy()

In [108]:
fam_1_2_electrical.head()

,Years,1 & 2 Fam Electrical Malfunction Fires,1 & 2 Fam Electrical Malfunction Injuries,1 & 2 Fam Electrical Malfunction Death
0,2003-01-01,22600,695,335
1,2004-01-01,23300,735,315
2,2005-01-01,24200,915,270
3,2006-01-01,25600,795,275
4,2007-01-01,26500,905,270

In [111]:
fire_cost = cause_and_effect_fires[
    ['Years',
     '1 & 2 Fam Heating Cost', 
     'Multi Fam Heating Cost', 
     '1 & 2 Fam Cooking Cost',
     'MultiFam Cooking Cost',
     '1 & 2 Fam Electrical Malfunction Cost']
].copy()
fire_cost = fire_cost.loc[:,~fire_cost.columns.duplicated()].copy()

In [113]:
fire_cost.head()

,Years,1 & 2 Fam Heating Cost,Multi Fam Heating Cost,1 & 2 Fam Cooking Cost,MultiFam Cooking Cost,1 & 2 Fam Electrical Malfunction Cost
0,2003-01-01,435200000,35300000,266600000,96600000,1033800000
1,2004-01-01,332800000,60600000,220500000,85900000,1075900000
2,2005-01-01,338600000,52800000,265500000,88700000,1276700000
3,2006-01-01,377100000,32900000,229300000,84700000,1135500000
4,2007-01-01,285600000,33500000,214400000,75000000,1106300000

### 5. Graphs for analysis

Now that all the tables are ready, I went ahead and made several types of charts.

In [89]:
allfires = total_fires.reset_index().melt('Years')
allfires = allfires.drop(allfires[allfires['variable'] == 'index'].index)
alt.Chart(allfires, title = "Number of Fires in Residential Homes").mark_line().encode(
    x='Years',
    y='value',
    color='variable')

alt.Chart(...)

In [112]:
firecost = fire_cost.reset_index().melt('Years')
firecost = firecost.drop(firecost[firecost['variable'] == 'index'].index)
alt.Chart(firecost, title = "Fire Dollar Loss for Residential Homes").mark_line().encode(
    x='Years',
    y='value',
    color='variable')

alt.Chart(...)

In [122]:
famheat = fam_1_2_heating.reset_index().melt('Years')
famheat = famheat.drop(famheat[famheat['variable'] == 'index'].index)
alt.Chart(famheat, title = "1 and 2 Family Residential Fires Caused by Heating and their Effects").mark_bar(opacity = 0.5).encode(
    x='Years',
    y='value',
    color=alt.Color('variable',
                    scale=alt.Scale(
                        range=['black', '#F3D5FA', 'red'])))

alt.Chart(...)

In [126]:
mfamheat = multi_fam_heating.reset_index().melt('Years')
mfamheat = mfamheat.drop(mfamheat[mfamheat['variable'] == 'index'].index)
alt.Chart(mfamheat, title = "Multi Family Residential Fires Caused by Heating and their Effects").mark_bar(opacity = 0.5).encode(
    x='Years',
    y='value',
    color=alt.Color('variable',
                    scale=alt.Scale(
                        range=['black', '#F3D5FA', 'red'])))

alt.Chart(...)

In [129]:
famcook = fam_1_2_cooking.reset_index().melt('Years')
famcook = famcook.drop(famcook[famcook['variable'] == 'index'].index)
alt.Chart(famcook, title = "1 and 2 Family Residential Fires Caused by Cooking and their Effects").mark_bar(opacity = 0.5).encode(
    x='Years',
    y='value',
    color=alt.Color('variable',
                    scale=alt.Scale(
                        range=['black', '#F3D5FA', 'red']))
)

alt.Chart(...)

In [132]:
mfamcook = multi_fam_cooking.reset_index().melt('Years')
mfamcook = mfamcook.drop(mfamcook[mfamcook['variable'] == 'index'].index)
alt.Chart(mfamcook, title = "Multi Family Residential Fires Caused by Cooking and their Effects").mark_bar(opacity =0.5).encode(
    x='Years',
    y='value',
    color=alt.Color('variable',
                    scale=alt.Scale(
                        range=['black', '#F3D5FA', 'red'])))

alt.Chart(...)

In [135]:
famelec = fam_1_2_electrical.reset_index().melt('Years')
famelec = famelec.drop(famelec[famelec['variable'] == 'index'].index)
alt.Chart(famelec, title = "1 and 2 Family Residential Fires Caused by Electrical Malfunctions and their Effects").mark_bar(opacity = 0.5).encode(
    x='Years',
    y='value',
    color=alt.Color('variable',
                    scale=alt.Scale(
                        range=['black', '#F3D5FA', 'red']))
)

alt.Chart(...)

### 6. My analysis

Like I mentioned in my cleaning up notebook, I wanted to see what was causing fires the most for people. So when I figured out which ones it was, I narrowed down my scope and wanted to see what the effects of those fires are. 

Based off my first graph, I wanted to see the trend of fire rates throughout the years. Was it consistent? Did things change and if they did why did they change? Most of the data was pretty much consistent over a period of time except for there being some decreases in heating fires for both multifamily homes and 1 & 2 family homes. According to the definition of the causes, this probably means that children are playing with heat sources less or people in general or not playing with heat sources or fire that much anymore. 

Because the amount of fires was pretty much consistent year after year, I expected to see the same for the fire dollar loss. However the data didn't really follow those lines. The most costly cause of fire was an electrical malfunction, even though that didn't cause nearly as many fires as cooking and playing with a heat source. However, this probably isn't suprising because there seems to be some research out there that electrical fires tend to cost the most out of other fires in terms of money, life, and losing valuables (https://www.afcisafety.org/files/realcostelectricalfire.pdf. 

Besides those graphs, my main focus was on the other ones, which dives into the causes of the fires and the injuries and deaths that occur from them. I did five different charts to show the five different causes I focused on. Based on these graphs, cooking fires seem to cause more injuries than death, which is probably explained by the fact that people are usually attentive and awake when they or someone in the building is cooking which means that people can evacuate faster. The amount of deaths did increase a little bit for fires caused by playing with a heat source. This can probably be explained by how children are usually the ones to be killed in these fires, maybe because they are the ones playing with the heat source or for some othe reason (https://sfm.illinois.gov/content/dam/soi/en/web/sfm/sfmdocuments/documents/homevictimsfactsheet.pdf). The last graph was a little bit suprising though. Even though there were less fires caused by electrical malfunction than cooking, it caused more injuries and deaths. This probably goes hand in hand with costs. Sometimes people aren't prepared for these types of fires or are not using equipment in their house that can increase their chance of escaping, which can explain the higher numbers of death and injury (https://www.afcisafety.org/files/realcostelectricalfire.pdf). Overall, I think exploring the electrical malfunctions peaked my interest and can be something more for me to look into.